#!/bin/sh
# Copyright (c) 2015 Marcus Downing <marcus.downing@gmail.com>
# Released under the 2-clause BSD license.

. efunctions_ecolors
efunctions_indent

if [ ! -z "$GOOD" ] ; then
	tput ll
fi

if [ $EBEGIN_NO_NEWLINE ] ; then
	echo -n "$NORMAL $GOOD*$NORMAL $@$NORMAL... "
else
	echo "$NORMAL $GOOD*$NORMAL $@$NORMAL..."
fi
