#!/bin/sh
# Copyright (c) 2015 Marcus Downing <marcus.downing@gmail.com>
# Released under the 2-clause BSD license.

P=${1:-0}
[ "$2" != "" ] && MSG="$(echo $@ | cut -d ' ' -f 2-)" || MSG=""

. efunctions_ecolors

if [ "$P" -ne 0 ]
then
  if [ "$MSG" != "" ]
  then
    eerror "$MSG"
  fi
fi

if [ ! -z "$GOOD" ] ; then
	COLS=$(tput cols)
	COLS=$(($COLS - 7))
	tput ll
	tput cuu1
	tput cuf $COLS
fi

"$EFUNCTIONS_ECHO" -n "${BRACKET}["

if [ "$P" -eq 0 ]
then
  "$EFUNCTIONS_ECHO" -n "${GOOD} ok"
else
  "$EFUNCTIONS_ECHO" -n "${BAD} !!"
fi
"$EFUNCTIONS_ECHO" " ${BRACKET}]${NORMAL} "

if [ ! -z "$GOOD" ] ; then
	tput sgr0
	tput ll
fi

exit $P
