#!/bin/sh
# Copyright (c) 2015 Marcus Downing <marcus.downing@gmail.com>
# Released under the 2-clause BSD license.

. efunctions_ecolors
efunctions_indent

if [ ! -z "$GOOD" ] ; then
	tput ll 1>&2
fi
"$EFUNCTIONS_ECHO" "$NORMAL $BAD*$NORMAL $@$NORMAL" 1>&2
