#!/bin/sh
# Copyright (c) 2015 Marcus Downing <marcus.downing@gmail.com>
# Released under the 2-clause BSD license.

EINFO_INDENT=${EINFO_INDENT:-0}
for I in `seq 1 $EINFO_INDENT`
do
  echo -n " "
done
