#!/bin/sh
# Copyright (c) 2015 Marcus Downing <marcus.downing@gmail.com>
# Released under the 2-clause BSD license.

EINFO_INDENT=${EINFO_INDENT:-0}
if [ "$EINFO_INDENT" -gt "0" ]; then
  for I in `seq 1 $EINFO_INDENT`
  do
    "$EFUNCTIONS_ECHO" -n " "
  done
fi