#!/bin/sh
# Copyright (c) 2015 Marcus Downing <marcus.downing@gmail.com>
# Released under the 2-clause BSD license.

. efunctions_ecolors
PREFIX="$(efunctions_indent)"

case "$1" in
  info|einfo)
    PREFIX="$PREFIX $GOOD*$NORMAL "
    ;;
  warn|ewarn)
    PREFIX="$PREFIX $WARN*$NORMAL "
    ;;
  error|eerror)
    PREFIX="$PREFIX $BAD*$NORMAL "
    ;;
  *)
    PREFIX="$PREFIX  "
esac

while read LINE; do
  echo "$LINE" | sed "s/^/$PREFIX/"
done
