#!/bin/sh
# Copyright (c) 2015 Marcus Downing <marcus.downing@gmail.com>
# Released under the 2-clause BSD license.

P=${1:-0}
MSG="$("$EFUNCTIONS_ECHO" $@ | cut -d ' ' -f 2-)"

. efunctions_ecolors

if [ "$P" -ne 0 ]
then
  if [ "$MSG" != "" ]
  then
    ewarn "$MSG"
  fi
fi

if [ ! -z "$GOOD" ] ; then
	COLS=$(tput cols)
	COLS=$(($COLS - 7))
	tput ll 1>&2
	tput cuu1 1>&2
	tput cuf $COLS 1>&2
fi

"$EFUNCTIONS_ECHO" -n "${BRACKET}[" 1>&2

if [ "$P" -eq 0 ]
then
  "$EFUNCTIONS_ECHO" -n "${GOOD} ok" 1>&2
else
  "$EFUNCTIONS_ECHO" -n "${BAD} !!" 1>&2
fi
"$EFUNCTIONS_ECHO" " ${BRACKET}]${NORMAL} " 1>&2

if [ ! -z "$GOOD" ] ; then
	tput sgr0 1>&2
	tput ll 1>&2
fi

exit $P
