#!/bin/sh
# Copyright (c) 2015 Marcus Downing <marcus.downing@gmail.com>
# Released under the 2-clause BSD license.

P=${1:-0}
MSG="$(echo $@ | cut -d ' ' -f 2-)"

. efunctions_ecolors

if [ "$P" -ne 0 ]
then
  if [ "$MSG" != "" ]
  then
    ewarn "$MSG"
  fi
fi

if [ ! -z "$GOOD" ] ; then
	COLS=$(tput cols)
	COLS=$(($COLS - 7))
	tput ll
	tput cuu1
	tput cuf $COLS
fi

echo -n "${BRACKET}["

if [ "$P" -eq 0 ]
then
  echo -n "${GOOD} ok"
else
  echo -n "${BAD} !!"
fi
echo " ${BRACKET}]${NORMAL} "

if [ ! -z "$GOOD" ] ; then
	tput sgr0
	tput ll
fi

exit $P
